### PR TITLE
Use rake ~> 13.0 av development dependency in gemspec

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR

- updates rake ~uses a looser `rake` dependency description in the gemspec, in order to allow ruby-head and other New Ruby versions to pass their tests.~ (The issue was that: Rake 10.5 uses now-removed methods.)
- excludes Ruby versions that are too old for that Rake from the CI matrix.

This gets us to 📗  green.

bild

[Image credit: lionel abrial](https://unsplash.com/photos/gUPIPcGCg28), shown here under the [Unsplash License](https://unsplash.com/license).

### CODE REVIEW

**Comment by steveklabnik** [comment]
This may cause breakage when a `0.11` comes out though, right? I am very wary of `>` in specifications. Hmm.

**Comment by olleolleolle** [comment]
@steveklabnik 13.0.6 is the current Rake, or are we talking about different things here?

**Comment by steveklabnik** [comment]
Sorry I meant 11.0.0. I haven't really used Ruby in... a long time, at this point (if you couldn't tell by this version constraint, hehe), so I don't instantly know what the latest versions are, I just went with the next one after what was written in the gemspec.

In general, using bare `>` in gemspecs is a bad idea because it means you can pull in semver-incompatible changes, which means upstream can break you at any time. Rake is *extremely* stable and so I doubt that it will do so, it just kinda gives me pause generally.

I probably will just get over it and accept this, but maybe there's also another way here.

**Comment by olleolleolle** [comment]
@steveklabnik Alright, let's use releases are any good: this change uses the latest release of Rake, 13.0 series.

That made us drop support for a few ancient Ruby versions - so I changed the CI matrix to reflect that.

**Comment by steveklabnik** [comment]
Thanks again for this, I've merged https://github.com/steveklabnik/request_store/pull/89 instead. So sorry that I don't have a ton of time for this gem.

**Pull request closed without merging**
