### PR TITLE
#23 Clearing request store after each request

### PR DESCRIPTION
**Pull request by afn**

### CODE REVIEW

**Comment by Fivell** [comment]
@steveklabnik , what is the reason of this behaviour?

**Comment by Fivell** [comment]
Let's say I have such code.


@steveklabnik, there is one more problem I found after debugging.
If I'm using Enumerator for response. Let's say I have such code in controller.

```
    filename = controller_name.downcase
    headers['X-Accel-Buffering'] = 'no'
    headers['Content-Type'] ||= 'text/csv'
    headers['Content-Disposition'] = "attachment; filename=#{filename}.csv"
    headers['Content-Transfer-Encoding'] = 'binary'
    headers['Last-Modified'] = Time.now.ctime.to_s
    self.status = 200
    self.response_body = Enumerator.new &block
```

under the hood it will use sort of ```Rack::BodyProxy``` that will evaluate <b>after</b> middleware will cleanup request store .
So if this block will populate variables in request store they will be not cleanup. And next request will contain stuff from previous one.

**Comment by steveklabnik** [comment]
see the linked https://github.com/steveklabnik/request_store/issues/23

**Comment by Fivell** [comment]
@steveklabnik , see my comment above, from issue I see

>> it would be prudent to clear the RequestStore not just before, but also after, each request.

but this PR removes cleaning before request, that's why it became not thread safety again.

**Comment by steveklabnik** [comment]
If you continue to read the discussion though, we had decided after was enough.

I'm not saying you're right or wrong here, just trying to provide said justification.

**Comment by Fivell** [comment]
@steveklabnik , to clarify. When request store cleaning data (after each request in middleware) it doesn't mean that there is no code that can populate it again ( yes still in the same request).

**Pull request merged**
